### PR TITLE
Update application.js

### PR DESCRIPTION
**Pull request by vitaly-t**
No need to include or use `pg` as a separate package. It is encapsulated within `pg-promise` as property `pg` ;)

You can remove `pg` from your package.json also ;)

### CODE REVIEW

**Comment by Klathmon** [comment]
Oh cool, thanks!

**Comment by vitaly-t** [comment]
@Klathmon There were changes to this with [version 3.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.5.0)

At long last, Native Bindings have been added. If you upgrade to it, and decide to use them, then you need to replace `pgImport.pg.native` with just `pgImport.pg`, which in case of native bindings within pg-promise will automatically be an instance of `pg-native`.

**Comment by Klathmon** [comment]
will it gracefully fallback to the pure-js bindings if the native package isn't (or couldn't be) installed?

**Comment by vitaly-t** [comment]
If you specify the new option `pgNative`, but do not install `pg-native`, it will bomb, as it should.

**Comment by vitaly-t** [comment]
These changes have been finalized in [version 3.5.5](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.5.5). You would continue using `pgImport.pg.native` to access it whenever needed.

However, you may find this issue of interest: https://github.com/brianc/node-postgres/issues/981

**Comment by vitaly-t** [comment]
All that mess have been finally solved in [version 3.7.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.7.0) there has been lots of input from the `pg` author also.

**Pull request merged**
